clone_depth: 50

platform:
  - x86
  - x64

image:
  - Visual Studio 2015
  - Visual Studio 2017

configuration:
  - Debug
  - Release

environment:
  DEPS_DIR: '%APPVEYOR_BUILD_FOLDER%\deps'

install:
  - cmake --version

  ############################################################################
  # CMake generator setup
  ############################################################################
  - set GENERATOR=Unknown
  - ps: |
      if ("$env:APPVEYOR_JOB_NAME" -match "Image: Visual Studio 2015") {
        $env:GENERATOR="Visual Studio 14 2015"
      } else {
        $env:GENERATOR="Visual Studio 15 2017"
      }
      if ($env:PLATFORM -eq "x64") {
        $env:GENERATOR="$env:GENERATOR Win64"
      }
  - echo %GENERATOR%

  ############################################################################
  # Install all external dependencies to %DEPS_DIR%
  ############################################################################
  - if not exist %DEPS_DIR% mkdir %DEPS_DIR%
  - cd %DEPS_DIR%

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake . -Bbuild11 -G "%GENERATOR%" -DWILDCARDS_BUILD_EXAMPLES=ON
  - cmake . -Bbuild14 -G "%GENERATOR%" -DWILDCARDS_BUILD_EXAMPLES=ON -DWILDCARDS_USE_CXX_14=ON
  - cmake . -Bbuild17 -G "%GENERATOR%" -DWILDCARDS_BUILD_EXAMPLES=ON -DWILDCARDS_USE_CXX_17=ON

build_script:
  - cmake --build build11 --config %CONFIGURATION% -- /m /v:minimal
  - cmake --build build14 --config %CONFIGURATION% -- /m /v:minimal
  - cmake --build build17 --config %CONFIGURATION% -- /m /v:minimal

test_script:
  - cd build11
  - ctest --output-on-failure --build-config %CONFIGURATION%
  - cd ..
  - cd build14
  - ctest --output-on-failure --build-config %CONFIGURATION%
  - cd ..
  - cd build17
  - ctest --output-on-failure --build-config %CONFIGURATION%
