version: 1.3.0.{build}

init:
  - git config --global core.autocrlf true

environment:
  matrix:
    - compiler: Visual Studio 14 2015
      generator: "Visual Studio 14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

    - compiler: Visual Studio 14 2015
      generator: "Visual Studio 14 2015 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

    - compiler: Visual Studio 15 2017
      generator: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - compiler: Visual Studio 15 2017
      generator: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - compiler: MinGW 6.3
      generator: "MinGW Makefiles"
      mingw_path: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

    - compiler: MinGW 6.3
      generator: "MinGW Makefiles"
      mingw_path: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

    - compiler: MinGW 7.2
      generator: "MinGW Makefiles"
      mingw_path: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

    - compiler: MinGW 7.3
      generator: "MinGW Makefiles"
      mingw_path: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

configuration:
  - Debug
  - Release

CXX_STANDARD:
  - 11
  - 14
  - 17

install:
  - cmake --version

  #######################
  # CMake generator setup
  #######################

  - ps: |
      if ($env:generator -eq "MinGW Makefiles") {
        # git bash conflicts with MinGW Makefiles
        $env:path = $env:path.replace("C:\Program Files\Git\usr\bin;", "")
        $env:path += ";$env:mingw_path"
      }
  - echo %generator%

before_build:
  - ps: |
      cd $env:APPVEYOR_BUILD_FOLDER
      & cmake . -Bbuild -G "$env:generator" -DWILDCARDS_BUILD_EXAMPLES=ON -DWILDCARDS_CXX_STANDARD=$evn:CXX_STANDARD
      if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
      }

build_script:
  - ps: |
      $cmake_parallel = if ($env:generator -eq "MinGW Makefiles") {"-j2"} else {"/m"}
      cmake --build build --config $env:configuration -- $cmake_parallel
      if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
      }

test_script:
  - ps: |
      cd build
      & ctest --output-on-failure --build-config $env:CONFIGURATION
      if ($LastExitCode -ne 0) {
        throw "Exec: $ErrorMessage"
      }
