init:
  - git config --global core.autocrlf true

image:
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  matrix:
    - CXX_STANDARD: 11
    - CXX_STANDARD: 14
    - CXX_STANDARD: 17

platform:
  - x32
  - x64

configuration:
  - Debug
  - Release

install:
  - cmake --version

  ############################################################################
  # CMake generator setup
  ############################################################################
  - set GENERATOR=Unknown
  - ps: |
      if ("$env:APPVEYOR_JOB_NAME" -match "Image: Visual Studio 2015") {
        $env:GENERATOR="Visual Studio 14 2015"
      } else {
        $env:GENERATOR="Visual Studio 15 2017"
      }
      if ($env:PLATFORM -eq "x64") {
        $env:GENERATOR="$env:GENERATOR Win64"
      }
  - echo %GENERATOR%

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake . -Bbuild -G "%GENERATOR%" -DWILDCARDS_BUILD_EXAMPLES=ON -DWILDCARDS_CXX_STANDARD=%CXX_STANDARD%

build_script:
  - cmake --build build --config %CONFIGURATION% -- /m /v:minimal

test_script:
  - cd build
  - ctest --output-on-failure --build-config %CONFIGURATION%
