# Based on https://github.com/Microsoft/GSL/blob/master/.travis.yml

language: cpp
sudo: false

os: linux
dist: trusty

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

matrix:
  include:

    ##############
    # Clang on OSX
    ##############

    # XCode 9
    - env: COMPILER=clang++ BUILD_TYPE=Debug CXX_STANDARD=11
      os: osx
      osx_image: xcode9
      compiler: clang

    - env: COMPILER=clang++ BUILD_TYPE=Debug CXX_STANDARD=14
      os: osx
      osx_image: xcode9
      compiler: clang

    - env: COMPILER=clang++ BUILD_TYPE=Debug CXX_STANDARD=17
      os: osx
      osx_image: xcode9
      compiler: clang

    - env: COMPILER=clang++ BUILD_TYPE=Release CXX_STANDARD=11
      os: osx
      osx_image: xcode9
      compiler: clang

    - env: COMPILER=clang++ BUILD_TYPE=Release CXX_STANDARD=14
      os: osx
      osx_image: xcode9
      compiler: clang

    - env: COMPILER=clang++ BUILD_TYPE=Release CXX_STANDARD=17
      os: osx
      osx_image: xcode9
      compiler: clang

    ################
    # Clang on Linux
    ################

    # Clang 3.8
    - env: COMPILER=clang++-3.8 BUILD_TYPE=Debug CXX_STANDARD=11
      addons: &clang38
        apt:
          packages:
            - clang-3.8
          sources:
            - llvm-toolchain-trusty-3.8

    - env: COMPILER=clang++-3.8 BUILD_TYPE=Debug CXX_STANDARD=14
      addons: *clang38

    - env: COMPILER=clang++-3.8 BUILD_TYPE=Debug CXX_STANDARD=17
      addons: *clang38

    - env: COMPILER=clang++-3.8 BUILD_TYPE=Release CXX_STANDARD=11
      addons: *clang38

    - env: COMPILER=clang++-3.8 BUILD_TYPE=Release CXX_STANDARD=14
      addons: *clang38

    - env: COMPILER=clang++-3.8 BUILD_TYPE=Release CXX_STANDARD=17
      addons: *clang38

    # Clang 3.9
    - env: COMPILER=clang++-3.9 BUILD_TYPE=Debug CXX_STANDARD=11
      addons: &clang39
        apt:
          packages:
            - clang-3.9
          sources:
            - llvm-toolchain-trusty-3.9

    - env: COMPILER=clang++-3.9 BUILD_TYPE=Debug CXX_STANDARD=14
      addons: *clang39

    - env: COMPILER=clang++-3.9 BUILD_TYPE=Debug CXX_STANDARD=17
      addons: *clang39

    - env: COMPILER=clang++-3.9 BUILD_TYPE=Release CXX_STANDARD=11
      addons: *clang39

    - env: COMPILER=clang++-3.9 BUILD_TYPE=Release CXX_STANDARD=14
      addons: *clang39

    - env: COMPILER=clang++-3.9 BUILD_TYPE=Release CXX_STANDARD=17
      addons: *clang39

    # Clang 4.0
    - env: COMPILER=clang++-4.0 BUILD_TYPE=Debug CXX_STANDARD=11
      addons: &clang40
        apt:
          packages:
            - clang-4.0
          sources:
            - llvm-toolchain-trusty-4.0

    - env: COMPILER=clang++-4.0 BUILD_TYPE=Debug CXX_STANDARD=14
      addons: *clang40

    - env: COMPILER=clang++-4.0 BUILD_TYPE=Debug CXX_STANDARD=17
      addons: *clang40

    - env: COMPILER=clang++-4.0 BUILD_TYPE=Release CXX_STANDARD=11
      addons: *clang40

    - env: COMPILER=clang++-4.0 BUILD_TYPE=Release CXX_STANDARD=14
      addons: *clang40

    - env: COMPILER=clang++-4.0 BUILD_TYPE=Release CXX_STANDARD=17
      addons: *clang40

    # Clang 5.0
    - env: COMPILER=clang++-5.0 BUILD_TYPE=Debug CXX_STANDARD=11
      addons: &clang50
        apt:
          packages:
            - clang-5.0
          sources:
            - llvm-toolchain-trusty-5.0

    - env: COMPILER=clang++-5.0 BUILD_TYPE=Debug CXX_STANDARD=14
      addons: *clang50

    - env: COMPILER=clang++-5.0 BUILD_TYPE=Debug CXX_STANDARD=17
      addons: *clang50

    - env: COMPILER=clang++-5.0 BUILD_TYPE=Release CXX_STANDARD=11
      addons: *clang50

    - env: COMPILER=clang++-5.0 BUILD_TYPE=Release CXX_STANDARD=14
      addons: *clang50

    - env: COMPILER=clang++-5.0 BUILD_TYPE=Release CXX_STANDARD=17
      addons: *clang50

    # Clang 6.0
    - env: COMPILER=clang++-6.0 BUILD_TYPE=Debug CXX_STANDARD=11
      addons: &clang60
        apt:
          packages:
            - clang-6.0
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0

    - env: COMPILER=clang++-6.0 BUILD_TYPE=Debug CXX_STANDARD=14
      addons: *clang60

    - env: COMPILER=clang++-6.0 BUILD_TYPE=Debug CXX_STANDARD=17
      addons: *clang60

    - env: COMPILER=clang++-6.0 BUILD_TYPE=Release CXX_STANDARD=11
      addons: *clang60

    - env: COMPILER=clang++-6.0 BUILD_TYPE=Release CXX_STANDARD=14
      addons: *clang60

    - env: COMPILER=clang++-6.0 BUILD_TYPE=Release CXX_STANDARD=17
      addons: *clang60

    ##############
    # GCC on Linux
    ##############

    # GCC 4.8
    - env: COMPILER=g++-4.8 BUILD_TYPE=Debug CXX_STANDARD=11
      addons: &gcc48
        apt:
          packages:
            - g++-4.8
          sources: &sources
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-4.8 BUILD_TYPE=Debug CXX_STANDARD=14
      addons: *gcc48

    - env: COMPILER=g++-4.8 BUILD_TYPE=Debug CXX_STANDARD=17
      addons: *gcc48

    - env: COMPILER=g++-4.8 BUILD_TYPE=Release CXX_STANDARD=11
      addons: *gcc48

    - env: COMPILER=g++-4.8 BUILD_TYPE=Release CXX_STANDARD=14
      addons: *gcc48

    - env: COMPILER=g++-4.8 BUILD_TYPE=Release CXX_STANDARD=17
      addons: *gcc48

    # GCC 4.9
    - env: COMPILER=g++-4.9 BUILD_TYPE=Debug CXX_STANDARD=11
      addons: &gcc49
        apt:
          packages:
            - g++-4.9
          sources: &sources
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-4.9 BUILD_TYPE=Debug CXX_STANDARD=14
      addons: *gcc49

    - env: COMPILER=g++-4.9 BUILD_TYPE=Debug CXX_STANDARD=17
      addons: *gcc49

    - env: COMPILER=g++-4.9 BUILD_TYPE=Release CXX_STANDARD=11
      addons: *gcc49

    - env: COMPILER=g++-4.9 BUILD_TYPE=Release CXX_STANDARD=14
      addons: *gcc49

    - env: COMPILER=g++-4.9 BUILD_TYPE=Release CXX_STANDARD=17
      addons: *gcc49

    # GCC 5
    - env: COMPILER=g++-5 BUILD_TYPE=Debug CXX_STANDARD=11
      addons: &gcc5
        apt:
          packages:
            - g++-5
          sources: &sources
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-5 BUILD_TYPE=Debug CXX_STANDARD=14
      addons: *gcc5

    - env: COMPILER=g++-5 BUILD_TYPE=Debug CXX_STANDARD=17
      addons: *gcc5

    - env: COMPILER=g++-5 BUILD_TYPE=Release CXX_STANDARD=11
      addons: *gcc5

    - env: COMPILER=g++-5 BUILD_TYPE=Release CXX_STANDARD=14
      addons: *gcc5

    - env: COMPILER=g++-5 BUILD_TYPE=Release CXX_STANDARD=17
      addons: *gcc5

    # GCC 6
    - env: COMPILER=g++-6 BUILD_TYPE=Debug CXX_STANDARD=11
      addons: &gcc6
        apt:
          packages:
            - g++-6
          sources: *sources

    - env: COMPILER=g++-6 BUILD_TYPE=Debug CXX_STANDARD=14
      addons: *gcc6

    - env: COMPILER=g++-6 BUILD_TYPE=Debug CXX_STANDARD=17
      addons: *gcc6

    - env: COMPILER=g++-6 BUILD_TYPE=Release CXX_STANDARD=11
      addons: *gcc6

    - env: COMPILER=g++-6 BUILD_TYPE=Release CXX_STANDARD=14
      addons: *gcc6

    - env: COMPILER=g++-6 BUILD_TYPE=Release CXX_STANDARD=17
      addons: *gcc6

    # GCC 7
    - env: COMPILER=g++-7 BUILD_TYPE=Debug CXX_STANDARD=11
      addons: &gcc7
        apt:
          packages:
            - g++-7
          sources: *sources

    - env: COMPILER=g++-7 BUILD_TYPE=Debug CXX_STANDARD=14
      addons: *gcc7

    - env: COMPILER=g++-7 BUILD_TYPE=Debug CXX_STANDARD=17
      addons: *gcc7

    - env: COMPILER=g++-7 BUILD_TYPE=Release CXX_STANDARD=11
      addons: *gcc7

    - env: COMPILER=g++-7 BUILD_TYPE=Release CXX_STANDARD=14
      addons: *gcc7

    - env: COMPILER=g++-7 BUILD_TYPE=Release CXX_STANDARD=17
      addons: *gcc7

    # GCC 8
    - env: COMPILER=g++-8 BUILD_TYPE=Debug CXX_STANDARD=11
      addons: &gcc8
        apt:
          packages:
            - g++-8
          sources: *sources

    - env: COMPILER=g++-8 BUILD_TYPE=Debug CXX_STANDARD=14
      addons: *gcc8

    - env: COMPILER=g++-8 BUILD_TYPE=Debug CXX_STANDARD=17
      addons: *gcc8

    - env: COMPILER=g++-8 BUILD_TYPE=Release CXX_STANDARD=11
      addons: *gcc8

    - env: COMPILER=g++-8 BUILD_TYPE=Release CXX_STANDARD=14
      addons: *gcc8

    - env: COMPILER=g++-8 BUILD_TYPE=Release CXX_STANDARD=17
      addons: *gcc8

install:
  - export CXX=${COMPILER}
  - ${CXX} --version

  - cmake --version

  - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
  - mkdir -p ${DEPS_DIR}
  - cd ${DEPS_DIR}

  - JOBS=2

  #############################################
  # [linux] Install the right version of libc++
  #############################################

  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" && "${CXX%%+*}" == "clang" ]]; then
      LLVM_INSTALL=${DEPS_DIR}/llvm/install
      if [[ -z "$(ls -A ${LLVM_INSTALL})" ]]; then
        if   [[ "${CXX}" == "clang++-3.8" ]]; then LLVM_VERSION=3.8.1;
        elif [[ "${CXX}" == "clang++-3.9" ]]; then LLVM_VERSION=3.9.1;
        elif [[ "${CXX}" == "clang++-4.0" ]]; then LLVM_VERSION=4.0.1;
        elif [[ "${CXX}" == "clang++-5.0" ]]; then LLVM_VERSION=5.0.2;
        elif [[ "${CXX}" == "clang++-6.0" ]]; then LLVM_VERSION=6.0.1;
        fi
        LLVM_URL=http://llvm.org/releases/${LLVM_VERSION}/llvm-${LLVM_VERSION}.src.tar.xz
        LIBCXX_URL=http://llvm.org/releases/${LLVM_VERSION}/libcxx-${LLVM_VERSION}.src.tar.xz
        LIBCXXABI_URL=http://llvm.org/releases/${LLVM_VERSION}/libcxxabi-${LLVM_VERSION}.src.tar.xz
        mkdir -p llvm llvm/build llvm/projects/libcxx llvm/projects/libcxxabi
        travis_retry wget -O - ${LLVM_URL} | tar --strip-components=1 -xJ -C llvm
        travis_retry wget -O - ${LIBCXX_URL} | tar --strip-components=1 -xJ -C llvm/projects/libcxx
        travis_retry wget -O - ${LIBCXXABI_URL} | tar --strip-components=1 -xJ -C llvm/projects/libcxxabi
        (cd llvm/build && cmake .. -DCMAKE_INSTALL_PREFIX=${LLVM_INSTALL})
        (cd llvm/build/projects/libcxx && make install -j${JOBS})
        (cd llvm/build/projects/libcxxabi && make install -j${JOBS})
      fi
      export CXXFLAGS="-isystem ${LLVM_INSTALL}/include/c++/v1"
      export LDFLAGS="-L ${LLVM_INSTALL}/lib -lc++ -lc++abi"
      export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${LLVM_INSTALL}/lib
    fi

before_script:
  - |
    cd ${TRAVIS_BUILD_DIR}
    cmake . -Bbuild -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DWILDCARDS_BUILD_EXAMPLES=ON -DWILDCARDS_CXX_STANDARD=${CXX_STANDARD}
    cmake --build build -- -j$JOBS

script:
  - |
    cd build
    ctest --output-on-failure -j${JOBS}
