# Based on https://github.com/Microsoft/GSL/blob/master/.travis.yml

language: cpp
sudo: false

os: linux
dist: trusty

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

matrix:
  include:

    ##############
    # Clang on OSX
    ##############

    # XCode 9
    - env: COMPILER=clang++ BUILD_TYPE=Debug
      os: osx
      osx_image: xcode9
      compiler: clang

    - env: COMPILER=clang++ BUILD_TYPE=Release
      os: osx
      osx_image: xcode9
      compiler: clang

    ################
    # Clang on Linux
    ################

    # Clang 4.0
    - env: COMPILER=clang++-4.0 BUILD_TYPE=Debug
      addons: &clang40
        apt:
          packages:
            - clang-4.0
          sources:
            - llvm-toolchain-trusty-4.0

    - env: COMPILER=clang++-4.0 BUILD_TYPE=Release
      addons: *clang40

    # Clang 5.0
    - env: COMPILER=clang++-5.0 BUILD_TYPE=Debug
      addons: &clang50
        apt:
          packages:
            - clang-5.0
          sources:
            - llvm-toolchain-trusty-5.0

    - env: COMPILER=clang++-5.0 BUILD_TYPE=Release
      addons: *clang50

    # Clang 6.0
    - env: COMPILER=clang++-6.0 BUILD_TYPE=Debug
      addons: &clang60
        apt:
          packages:
            - clang-6.0
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0

    - env: COMPILER=clang++-6.0 BUILD_TYPE=Release
      addons: *clang60

    ##############
    # GCC on Linux
    ##############

    # GCC 5
    - env: COMPILER=g++-5 BUILD_TYPE=Debug
      addons: &gcc5
        apt:
          packages:
            - g++-5
          sources: &sources
            - ubuntu-toolchain-r-test

    - env: COMPILER=g++-5 BUILD_TYPE=Release
      addons: *gcc5

    # GCC 6
    - env: COMPILER=g++-6 BUILD_TYPE=Debug
      addons: &gcc6
        apt:
          packages:
            - g++-6
          sources: *sources

    - env: COMPILER=g++-6 BUILD_TYPE=Release
      addons: *gcc6

    # GCC 7
    - env: COMPILER=g++-7 BUILD_TYPE=Debug
      addons: &gcc7
        apt:
          packages:
            - g++-7
          sources: *sources

    - env: COMPILER=g++-7 BUILD_TYPE=Release
      addons: *gcc7

    # GCC 8
    - env: COMPILER=g++-8 BUILD_TYPE=Debug
      addons: &gcc8
        apt:
          packages:
            - g++-8
          sources: *sources

    - env: COMPILER=g++-8 BUILD_TYPE=Release
      addons: *gcc8

install:
  - export CXX=${COMPILER}
  - ${CXX} --version

  - cmake --version

  - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
  - mkdir -p ${DEPS_DIR}
  - cd ${DEPS_DIR}

  - JOBS=2

  #############################################
  # [linux] Install the right version of libc++
  #############################################
  - |
    LLVM_INSTALL=${DEPS_DIR}/llvm/install
    if [[ "${TRAVIS_OS_NAME}" == "linux" && "${CXX%%+*}" == "clang" && -n "$(ls -A ${LLVM_INSTALL})" ]]; then
      if   [[ "${CXX}" == "clang++-3.8" ]]; then LLVM_VERSION=3.8.1;
      elif [[ "${CXX}" == "clang++-3.9" ]]; then LLVM_VERSION=3.9.1;
      fi
      LLVM_URL=http://llvm.org/releases/${LLVM_VERSION}/llvm-${LLVM_VERSION}.src.tar.xz
      LIBCXX_URL=http://llvm.org/releases/${LLVM_VERSION}/libcxx-${LLVM_VERSION}.src.tar.xz
      LIBCXXABI_URL=http://llvm.org/releases/${LLVM_VERSION}/libcxxabi-${LLVM_VERSION}.src.tar.xz
      mkdir -p llvm llvm/build llvm/projects/libcxx llvm/projects/libcxxabi
      travis_retry wget -O - ${LLVM_URL} | tar --strip-components=1 -xJ -C llvm
      travis_retry wget -O - ${LIBCXX_URL} | tar --strip-components=1 -xJ -C llvm/projects/libcxx
      travis_retry wget -O - ${LIBCXXABI_URL} | tar --strip-components=1 -xJ -C llvm/projects/libcxxabi
      (cd llvm/build && cmake .. -DCMAKE_INSTALL_PREFIX=${LLVM_INSTALL})
      (cd llvm/build/projects/libcxx && make install -j${JOBS})
      (cd llvm/build/projects/libcxxabi && make install -j${JOBS})
      export CXXFLAGS="-isystem ${LLVM_INSTALL}/include/c++/v1"
      export LDFLAGS="-L ${LLVM_INSTALL}/lib -l c++ -l c++abi"
      export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${LLVM_INSTALL}/lib
    fi

before_script:
  - |
    cd ${TRAVIS_BUILD_DIR}
    cmake . -Bbuild11 -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DWILDCARDS_BUILD_EXAMPLES=ON
    cmake --build build11 -- -j${JOBS}
    cmake . -Bbuild14 -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DWILDCARDS_BUILD_EXAMPLES=ON -DWILDCARDS_USE_CXX_14=ON
    cmake --build build14 -- -j${JOBS}
    cmake . -Bbuild17 -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DWILDCARDS_BUILD_EXAMPLES=ON -DWILDCARDS_USE_CXX_17=ON
    cmake --build build17 -- -j${JOBS}

script:
  - cd build11
  - ctest --output-on-failure -j${JOBS}
  - cd -
  - cd build14
  - ctest --output-on-failure -j${JOBS}
  - cd -
  - cd build17
  - ctest --output-on-failure -j${JOBS}
